version: "3"

services:
  heimdall:
    image: linuxserver/heimdall
    hostname: heimdall
    container_name: heimdall
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "${DOCKER_GW}:${HEIMDALL}:80"
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - '~/docker/heimdall/linuxserver-heimdall/config:/config'
