version: "3"

services:
  redis:
    image: redis:alpine
    hostname: redis-alpine
    container_name: redis-alpine
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    environment:
