version: "3"

services:
  homeassistant:
    image: homeassistant/raspberrypi4-homeassistant:stable
    container_name: homeassistant
    network_mode: host
    volumes:
      - '~/docker/home-assistant/homeassistant-raspberrypi4-homeassistant-stable:/config'
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
