version: "3"

services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: password
