version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    network_mode: bridge
    ports:
#      - "8000:8000"
      - "8111:9000"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    restart: unless-stopped

volumes:
  portainer_data:
    external: true
