version: "3"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    network_mode: bridge
    restart: unless-stopped
    ports:
#      - "8000:8000"
      - "${DOCKER_GW}:${PORTAINER}:9000"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/docker/portainer/portainer-portainer-ce/data:/data'
