version: "3"

services:
  portainer:
    image: portainer/agent
    container_name: portainer_agent
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
