version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "67:67/udp"
#      - "80:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'pihole'
    volumes:
      - '~/docker/pihole/pihole-pihole-latest/etc-pihole/:/etc/pihole/'
      - '~/docker/pihole/pihole-pihole-latest/etc-dnsmasq.d/:/etc/dnsmasq.d/'
#    cap_add:
#      - NET_ADMIN
#    restart: unless-stopped

networks:
  default:
    external:
      name: docker-network
